### ISSUE TITLE
Morph-Objekte sollten gefühlt mehr OOP Möglichkeiten anbieten

### ISSUE THREAD

**Issue by daniel-heg** [iisii-solutions-GmbH/commly#10]
Wenn ich die Aktivitäten einer Session abrufe, dann möchte ich eigentlich nicht per String-Vergleiche über die Typeable-Meta Felder herausfinden müssen (und dann noch richtig Casten) was für ein Typ von Aktivität das ist. 

Ich stelle mir hier irgendwie vor, dass ich einfach Funktionen wie
```php
public function getRelevantDetails(Activity $activity) {
  switch($activity) {
    case SMS: return $activity->content;
    case FILE: return $activity->path;
    ...
  }
}
``` 
schreiben können sollte. 

Oder alternativ, dass `SMS` und `FILE` beide ein Interface implementieren für `getContent()` o.ä. wobei dann Funktionen wie 

```php
$activities->map(function ($activity) {
   return $activity->getContent(); # returnt content für SMS und path für FILE
})
``` 

möglich wären. 

Geht das irgendwie oder muss man dafür extra eine Factory schreiben?

**Comment by floreean** [comment]
Also generell bin ich auch offen, dass wir  die Verwendung von Morph nochmal besprechen und ggfs. nochmal refactoren (nach der Demo).

Das Problem was du hier ansprichst ist aber relativ einfach zu lösen:

```php
...
    case SMS: return $activity->typeable->content;
    case FILE: return $activity->typeable->path;
...
```

also über **$activity->typeable** bekommst du immer das Type-Objekt.

**Comment by daniel-heg** [comment]
Du hast komplett recht, `$activity->typeable` wird schon richtig gecastet. Damit ist das so für mich perfekt.
